### ISSUE TITLE
App gets paused due to excessive memory usage

### ISSUE THREAD

**Issue by tanordheim** [ThomasHoussin/com.thomashoussin.ruuvitag#11]
Hi - and thanks for creating a Ruuvitag-app for Homey!

I'm running a Homey Pro with a dozen or so Ruuvitags, and I find that the Ruuvitag-app gets paused quite often - and I can only assume because of excessive resource usage. This is the memory usage of the app from the day today, as you can see it slowly crawls from the initial 15MB up to around 75MB, where the app gets paused. The sudden drops in memory usage in this graph is me either restarting the Ruuvitag-app or the Homey itself:

![image](https://user-images.githubusercontent.com/49933/188125175-f21ab6be-ebcf-48e8-9d2e-6ec5ba492107.png)

![image](https://user-images.githubusercontent.com/49933/188136704-e6cb3166-190d-4188-b79c-1342ac9eec3a.png)

Is this a known issue, and is there some known workaround I can use here apart from creating a flow to restart the app once it gets paused?

I'd be happy to create a PR for a fix if you point me in the right direction. I also just sent a couple of diagnostics reports:

- `78203552-25e7-4e22-b56a-6989771e5038` is a report created after a restart, when the app was consuming a somewhat low amount of memory - but increasing.
- `628f3f11-e42e-465f-aae2-9e1f3b4b9d21` is a report created once Homey has paused the app due to excessive memory usage.

**Comment by ThomasHoussin** [comment]
Thanks for the report. It seems related to the number of devices (with around 6 Ruuvi, app does not get paused) but I had a look and also have this increasing memory usage. I'll have a look into that.

**Comment by tanordheim** [comment]
Excellent! Let me know if i can contribute in any way.

**Comment by ThomasHoussin** [comment]
Hi. I made some changes in test version, you can try it here : https://homey.app/fr-fr/app/com.thomashoussin.ruuvitag/RuuviTag/test/

Tell me if it improves memory usage (or not)

**Comment by tanordheim** [comment]
Thanks @ThomasHoussin! I installed it right now, I'll update you on the results once it's been running a while.

**Comment by tanordheim** [comment]
@ThomasHoussin looks like the app has gotten suspended because of memory usage some time during yesterday afternoon/last night so the problem still persists even in the test version. Would you like me to send a new diagnostics report?

**Comment by ThomasHoussin** [comment]
No thanks, it's not needed for now. I'll have another look at that...

**Comment by ThomasHoussin** [comment]
@tanordheim I made a quick fix to try identifying the problem, could you try the latest test version ? Thanks

**Comment by tanordheim** [comment]
@ThomasHoussin sure ting! Installed v0.2.2 now, I'll report back - thanks 🙂

**Comment by tanordheim** [comment]
Same result, Homey pauses the app after running a little while 😔

**Comment by ThomasHoussin** [comment]
Hi. I noticed a large improvement in memory usage with the latest version (to be honest, I'm not sure it's related to the version or another change in Homey but you can give it a try).

![image](https://user-images.githubusercontent.com/6912005/226188238-31f01429-97a5-4084-b8fa-92481d975ee2.png)
