### ISSUE TITLE
Ruuvitags on Homey 2023

### ISSUE THREAD

**Issue by Jo-Rien** [ThomasHoussin/com.thomashoussin.ruuvitag#19]
Hello Thomas,

While portring my ruuvitags from a homey 2016 to my new homey 2023 i run into a problem. When trying to connect the ruuvitags to my homey 2023 i get the same error every time "Cannot read properties of null".
I tried several times and every time i get this same error. Am i doing something wrong or is there a problem with the ruuvitag homey app?

Best regards,

Jo-Rien

**Comment by ThomasHoussin** [comment]
I'll have a look. Could you tell me where in the process you have this message ? When scanning for new devices, when adding, etc.? 

Did you try the test version ?
Thanks

**Comment by Jo-Rien** [comment]
Hi Thomas,

 

I get this message when scanning for new devices, i have 3 ruuvitags but it doesn’t find any of them. In the homey 2016 it has no problems finding them.

 

Best regard,

 

Jo-Rien

 

Van: Thomas Houssin ***@***.*** 
Verzonden: zaterdag 6 mei 2023 08:55
Aan: ThomasHoussin/com.thomashoussin.ruuvitag
CC: Jo-Rien; Author
Onderwerp: Re: [ThomasHoussin/com.thomashoussin.ruuvitag] Ruuvitags on Homey 2023 (Issue #19)

 

I'll have a look. Could you tell me where in the process you have this message ? When scanning for new devices, when adding, etc.? Thanks

**Comment by ThomasHoussin** [comment]
Did you try the test version ?

**Comment by Jo-Rien** [comment]
Yes i did try the test version.

 

Van: Thomas Houssin ***@***.*** 
Verzonden: maandag 8 mei 2023 11:51
Aan: ThomasHoussin/com.thomashoussin.ruuvitag
CC: Jo-Rien; Author
Onderwerp: Re: [ThomasHoussin/com.thomashoussin.ruuvitag] Ruuvitags on Homey 2023 (Issue #19)

 

Did you try the test version ?

**Comment by ThomasHoussin** [comment]
Can you try the latest test version ? Thanks

**Comment by grobo** [comment]
I have the a similar issue. With homey pro 2023, and the Ruuvi Tag Pro. With newest test version aswell.
When scanning for new ruuvitag it does not find anything. Is the newer pro version of the tag not supported?

**Comment by Jo-Rien** [comment]
I still have this issue also, also with the new test version. But when reviewing the "known issues" on the athom website i found the following which might be related to this problem with ruuvitags on the Homey Pro 2023.

Quote:
"Bluetooth LE — Some devices might not be found, or an error appears while connecting"

So maybe thomas can check with Athom if this could cause the problem?

**Comment by ThomasHoussin** [comment]
> I have the a similar issue. With homey pro 2023, and the Ruuvi Tag Pro. With newest test version aswell. When scanning for new ruuvitag it does not find anything. Is the newer pro version of the tag not supported?

Do you have the message "Cannot read properties of null" or only no device found ?

**Comment by Jo-Rien** [comment]
I get both of them intermittend it seems.

**Comment by ThomasHoussin** [comment]
> I still have this issue also, also with the new test version. But when reviewing the "known issues" on the athom website i found the following which might be related to this problem with ruuvitags on the Homey Pro 2023.
> 
> Quote: "Bluetooth LE — Some devices might not be found, or an error appears while connecting"
> 
> So maybe thomas can check with Athom if this could cause the problem?

Do you still have the "Cannot read properties of null" message ? Could you please try sending me a report ? This seems to be an error in the app and not because of BLE issue

Yes I read about the BLE problems [here ](https://github.com/athombv/homey-apps-sdk-issues/issues/245) ; There's another problem, the custom timeout for BLE discovery has been removed in Homey v6.0.0 (a default timeout of 5 seconds is being use) ; if the ruuvitag is far from Homey, if may not be detected

**Comment by Jo-Rien** [comment]
I have made a report through the homey app, do you need the report number?

**Comment by ThomasHoussin** [comment]
No it's ok thanks

**Comment by grobo** [comment]
> > I have the a similar issue. With homey pro 2023, and the Ruuvi Tag Pro. With newest test version aswell. When scanning for new ruuvitag it does not find anything. Is the newer pro version of the tag not supported?
> 
> Do you have the message "Cannot read properties of null" or only no device found ?

I do only get the "device found" message.

**Comment by Jo-Rien** [comment]
I tried the 0.25 version, now i only get the "No new devices found". But still no ruuvitags get detected unfortunatly.

**Comment by ThomasHoussin** [comment]
Ok this fixed the error message. To improve ruuvitag detection : 
- reboot Homey
- put the Ruuvitag as close as possible from Homey
- if your Ruuvitag use RAWv2-slow (V2 firmware), switch to RAWv2-fast to improve detection (firmware V2)
- if your Ruuvitag use long battery lifetime firmware, switch to standard firmware to improve detection (firmware V3)

**Comment by grobo** [comment]
Can I use a Ruuvi tag pro with this App? Or is it only the old one that works?

**Comment by Jo-Rien** [comment]
Just to update, after testing all your sugestions it still did not work for me.
So today there was a new homey 2023 update, did not mention anything about bluetooth. Still i gave it a shot, and to my surprise all ruuvitags now could be found in a second and added without any problem
So i guess there was something in the homey firmware that prevented the ruuvitags from being added.

**Comment by ThomasHoussin** [comment]
Thanks that's a good news

> Can I use a Ruuvi tag pro with this App? Or is it only the old one that works?

Yes AFAIK the BLE protocol is the same, it should work (however I don't have Ruuvi tag pro to test)

**Comment by Mulnard** [comment]
How far can a tag be from the homey ? Doesn’t this works by wifi then ? As holey works as gateway ?

**Comment by RSHKwee** [comment]
I get the following error on Homey 2023 for all my Ruuvi tags:
"Missing Capabilty Listener: onoff"

The app version running is v0.2.5
