### ISSUE TITLE
Entering, exited continous by tag

### ISSUE THREAD

**Issue by Mulnard** [ThomasHoussin/com.thomashoussin.ruuvitag#24]
Hi,

lossing continu connexion with the ruuvi tag.
Sometimes for several hours.
Using it for sauna, so not usefull.

what could be the cause ?

**Comment by ThomasHoussin** [comment]
Hi

First guess would be distance. How far is the ruuvitag from Homey ? Do you
have the same problem if ruuvitag is closer ?

Thomas

**Comment by Mulnard** [comment]
Hi,

ok will try. But isn’t it working by wifi ?
Very good wifi in the sauna room.

i will take ruuvi out of sauna and put him closer to test.

**Comment by Mulnard** [comment]
Hi,
24h closer. Not leaving anymore.

how can this be solved ? Moving homey no option. Moving sauna hahahaha certainly no option.

does it not work by wifi ?

**Comment by Mulnard** [comment]
Could be adding homey extender closer tonthe ruuvi a solution ?
How many meters ?

**Comment by ThomasHoussin** [comment]
Hi. No it's not wifi, Ruuvitag works with BLE. 
No idea with homey extender ; looking at the Satellite mode, it looks like BLE is not listed so my guess would be no. 

You can have a look at the Ruuvi Gateway (I added the support for the Ruuvi Gateway in latest beta), it could do what you're looking for
