### ISSUE TITLE
Missing Capabilty Listener: onoff

### ISSUE THREAD

**Issue by RSHKwee** [ThomasHoussin/com.thomashoussin.ruuvitag#26]
On Homey 2023 the Ruuvi app gives an error message:
"Oeps... er is iets misgegaan bij het aansturen van Garage."
"Missing Capability Listener: onoff"

Ruuvi tag App version: v0.2.5

Model Homey Pro (Early 2023) Version 11.1.0 
App version 8.2.0.1.1481

The data is not read from Ruuvi tag...

**Comment by ThomasHoussin** [comment]
Cannot reproduce ; I indeed do not register a capability listener for onoff but according to sdk : When setable is false, your Device doesn't need to register a capability listener.
